apiVersion: external-secrets.io/v1beta1
kind: ClusterExternalSecret
metadata:
  name: foo
spec:
  namespaceSelector:
    matchLabels:
      secrets.examplerep.com/foo: "true"
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: aws-secrets-manager
      kind: ClusterSecretStore
    target:
      name: foo
      creationPolicy: Owner
    data:
      - secretKey: value
        remoteRef:
          key: foo
