apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project-cluster.yaml #SW0
  - openshift-gitops.yaml #SW1
  - openshift-external-secrets.yaml #SW2
  - open-cluster-management.yaml #SW3