apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - project-cluster.yaml #SW0
  - openshift-gitops.yaml #SW1
  - openshift-external-secrets.yaml #SW2
  - open-cluster-management.yaml #SW3
  - openshift-service-mesh.yaml #SW4
  - openshift-pipelines.yaml #SW5
  - openshift-cert-manager.yaml #SW6
  - redhat-quay.yaml #SW7