apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hub-config
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/examplerep/gitops-cluster-hub.git
    targetRevision: main
    path: manifests/config
  destination:
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: external-secrets.io
      kind: ClusterExternalSecret
      jsonPointers:
        - /spec/externalSecretSpec/data
        - /spec/namespaceSelector
    - group: external-secrets.io
      kind: ClusterSecretStore
      jsonPointers:
        - /spec/provider/aws/auth
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
